from __future__ import annotations

POLICY_ALLOW_LOW_RISK = "POLICY_ALLOW_LOW_RISK"
POLICY_DENY_HIGH_RISK = "POLICY_DENY_HIGH_RISK"
POLICY_REQUIRE_APPROVAL_HIGH_VALUE = "POLICY_REQUIRE_APPROVAL_HIGH_VALUE"
POLICY_EVALUATION_FAILED = "POLICY_EVALUATION_FAILED"

BUDGET_EXCEEDED_AGENT_RATE = "BUDGET_EXCEEDED_AGENT_RATE"
BUDGET_EXCEEDED_TOOL_RATE = "BUDGET_EXCEEDED_TOOL_RATE"
BUDGET_EVALUATION_FAILED = "BUDGET_EVALUATION_FAILED"

APPROVAL_DENIED = "APPROVAL_DENIED"
APPROVAL_PROCESS_FAILED = "APPROVAL_PROCESS_FAILED"

LEDGER_WRITE_FAILED_DECISION = "LEDGER_WRITE_FAILED_DECISION"
